[project]
authors = [{ name = "James O'Claire" }]
name = "hackernews-scraper"
description = "Crawl latest hackernews and store for more convenient api calling"
version = "0.1.2"
dependencies = ["litestar[standard]"]

[project.optional-dependencies]
dev = ["pre-commit", "bump2version"]

[build-system]
requires = ["setuptools", "wheel"]


[tool.isort]
profile = 'black'

[tool.ruff]
# Enable flake8-bugbear (`B`) rules.
select = ["E", "F", "B", "I", "N"]

# Never enforce `E501` (line length violations).
ignore = ["E501"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
